### ISSUE TITLE
cy.json (); height and width do not change

### ISSUE THREAD

**Issue by atom238** [iVis-at-Bilkent/cytoscape.js-node-editing#49]
Dear Team,
when I resize node with cytoscape-node-editing grapples the height and width data are not up-to-date. After using grapples, I try to read the current data, for example with below code:
`document.getElementById('save').addEventListener('click', function() {
  json = cy.json();
  console.log('Nodes:', cy.nodes().jsons());
  console.log('Edges:', cy.edges().jsons(
));`
but I can always see the data before resizing.
![cy-git](https://user-images.githubusercontent.com/39830182/189429071-d0441315-262f-4392-bd59-a1fdb466df2d.png)
Could you please check it ?

**Comment by hasanbalci** [comment]
I think, those `width` and `height` properties in your data are added by your application, because nodes in Cytoscape.js don't have width or height in their data by default and this extension also doesn't add those properties. This extension only changes css(style) `width` and `height` values on resize. If you want to update `width` and `height` properties in your data as well, you can use [events](https://github.com/iVis-at-Bilkent/cytoscape.js-node-editing#emitted-events) provided by this extension. For example, you can use resizeend event to update the width value in node's data based on the new width value in node's css.

**Comment by atom238** [comment]
@hasanbalci Thank you for your response.
I appreciate your support.
